name: hum

on:
  push:
    branches:
      - main

# Allow the built-in GITHUB_TOKEN to push to the gh-pages branch
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0

      - run: opam install . --deps-only --with-doc --with-test
      - run: opam exec -- dune build --profile=release
      - run: opam exec -- dune exec bin/site.exe -- build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.target
          publish_branch: gh-pages
          enable_jekyll: false
